const translations = {
  en: {
    intro_h2: "Hi! My name is <span>Olga Galanets.</span><br>I am <span>IT Project Manager.</span>",
    intro_p: "I am passionate about turning complex ideas into successful, streamlined solutions. Over the years, I’ve built extensive expertise in Project and Marketing management, Business process automation.",
    counter_experience: "20+",
    counter_experience_label: "Years Experience",
    counter_projects: "50+",
    counter_projects_label: "Completed Projects",
    experience_title: "Work History",
    education_title: "Education",
    courses_title: "Courses",
    contact_title: "Contact information",
    resume_button: "Resume",
    footer_text: "© 2025. All rights reserved.",
    sidebar_title: "IT Project Manager |<br>Digital Transformation |<br>R&D Innovation",

    // Experience entries
    exp_1_title: "Senior IT Project Manager",
    exp_1_subtitle: "International Data Spaces Association (IDSA)",
    exp_2_title: "IT Project Account Manager",
    exp_2_subtitle: "Sanwell",
    exp_3_title: "IT Project Account Manager",
    exp_3_subtitle: "PlayToMax",
    exp_4_title: "ERP Project Manager",
    exp_4_subtitle: "Awery Aviation Software",
    exp_5_title: "Software Release Coordinator",
    exp_5_subtitle: "Tallium Inc.",
    exp_6_title: "Project Manager",
    exp_6_subtitle: "Weltrade",
    exp_7_title: "Project Manager for Terrasoft CRM-System (Internship)",
    exp_7_subtitle: "Terrasoft",
    exp_8_title: "Project Manager – Business Development",
    exp_8_subtitle: "Bank Trust",
    exp_9_title: "Market expansion manager",
    exp_9_subtitle: "AVANGARDCO IPL",
    exp_10_title: "Head of Marketing and Business Development Group",
    exp_10_subtitle: "Kreditprombank",
    exp_11_title: "Chief Marketing Officer",
    exp_11_subtitle: "Marketing Department, Nadra Bank",
    exp_12_title: "Senior Manager",
    exp_12_subtitle: "PrivatBank",
    exp_13_title: "Chief Officer",
    exp_13_subtitle: "Dnipropetrovsk Regional State Administration",
    exp_14_title: "Assistant to the deputy (Internship)",
    exp_14_subtitle: "Committee on Rules of Procedure, Parliamentary Ethics and Organization of Work of the Verkhovna Rada of Ukraine",

    // Courses entries
    course_1_title: "Web-design",
    course_1_subtitle: "Coursera",
    course_2_title: "German Language",
    course_2_subtitle: "Perfekt Deutsch · VHS",
    course_3_title: "UX-Design",
    course_3_subtitle: "Web Academy",
    course_4_title: "Front-end development",
    course_4_subtitle: "Web Academy",
    course_5_title: "Quality Assurance (QA)",
    course_5_subtitle: "Web Academy",
    course_6_title: "Business Analysis",
    course_6_subtitle: "Web Academy",
    course_7_title: "Google Analytics",
    course_7_subtitle: "ITC School",
    course_8_title: "English Language",
    course_8_subtitle: "University of Cambridge ESOL · LSE Business Academy"
  },
  de: {
    intro_h2: "Hallo! Mein Name ist <span>Olga Galanets.</span><br>Ich bin <span>IT-Projektmanagerin.</span>",
    intro_p: "Ich setze mich leidenschaftlich dafür ein, komplexe Ideen in erfolgreiche, optimierte Lösungen umzuwandeln. Im Laufe der Jahre habe ich umfangreiche Erfahrungen im Projekt- und Marketingmanagement sowie in der Geschäftsprozessautomatisierung gesammelt.",
    counter_experience: "20+",
    counter_experience_label: "Jahre Erfahrung",
    counter_projects: "50+",
    counter_projects_label: "Abgeschlossene Projekte",
    experience_title: "Berufserfahrung",
    education_title: "Ausbildung",
    courses_title: "Kurse",
    contact_title: "Kontaktinformationen",
    resume_button: "Lebenslauf",
    footer_text: "© 2025. Alle Rechte vorbehalten.",
    sidebar_title: "IT-Projektmanagerin |<br>Digitale Transformation |<br>F&E Innovation",

    // Experience entries
    exp_1_title: "Senior IT-Projektmanagerin",
    exp_1_subtitle: "International Data Spaces Association (IDSA)",
    exp_2_title: "IT-Projekt Account Managerin",
    exp_2_subtitle: "Sanwell",
    exp_3_title: "IT-Projekt Account Managerin",
    exp_3_subtitle: "PlayToMax",
    exp_4_title: "ERP-Projektmanagerin",
    exp_4_subtitle: "Awery Aviation Software",
    exp_5_title: "Software Release Koordinatorin",
    exp_5_subtitle: "Tallium Inc.",
    exp_6_title: "Projektmanagerin",
    exp_6_subtitle: "Weltrade",
    exp_7_title: "Projektmanagerin für Terrasoft CRM-System (Praktikum)",
    exp_7_subtitle: "Terrasoft",
    exp_8_title: "Projektmanagerin – Geschäftsentwicklung",
    exp_8_subtitle: "Bank Trust",
    exp_9_title: "Managerin Markterweiterung",
    exp_9_subtitle: "AVANGARDCO IPL",
    exp_10_title: "Leiterin Marketing und Geschäftsentwicklung",
    exp_10_subtitle: "Kreditprombank",
    exp_11_title: "Marketingchefin",
    exp_11_subtitle: "Marketingabteilung, Nadra Bank",
    exp_12_title: "Senior Managerin",
    exp_12_subtitle: "PrivatBank",
    exp_13_title: "Leitende Beamtin",
    exp_13_subtitle: "Regionale Staatsverwaltung Dnipropetrowsk",
    exp_14_title: "Assistentin des Abgeordneten (Praktikum)",
    exp_14_subtitle: "Ausschuss für Geschäftsordnung, Ethik und Organisation der Arbeit der Werchowna Rada der Ukraine",

    // Courses entries
    course_1_title: "Web-Design",
    course_1_subtitle: "Coursera",
    course_2_title: "Deutsch Sprache",
    course_2_subtitle: "Perfekt Deutsch · VHS",
    course_3_title: "UX-Design",
    course_3_subtitle: "Web Academy",
    course_4_title: "Front-End Entwicklung",
    course_4_subtitle: "Web Academy",
    course_5_title: "Qualitätssicherung (QA)",
    course_5_subtitle: "Web Academy",
    course_6_title: "Business Analyse",
    course_6_subtitle: "Web Academy",
    course_7_title: "Google Analytics",
    course_7_subtitle: "ITC School",
    course_8_title: "Englisch Sprache",
    course_8_subtitle: "University of Cambridge ESOL · LSE Business Academy"
  }
};
